apiVersion: v1
kind: Service
metadata:
  name: benchmark-service
spec:
  selector:
    app: benchmark-app
  ports:
    - protocol: TCP
      port: 8080        # The port the service exposes
      targetPort: 8080  # The port your apps are listening on inside the container
  type: ClusterIP